colonize/models.py
import enum
from colonize import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    """ Funkce pro načtení přihlášeného uživatele

    Tato funkce načte uživatele z databáze podle předaného id

    :param int user_id: ID uživatele
    :return: Záznam uživatele
    """
    return User.query.filter_by(id_user=user_id).first()


class Gender(enum.Enum):
    """ Výčet pohlaví

    Třída uchovávající obě pohlaví, které lze uchovávat v databázi
    """
    MALE = 0
    FEMALE = 1


class Role(enum.Enum):
    """Výčet rolí

    Třída uchovávající možné role, které mohou uživatele mít
    """
    COLONIZER = 0
    MAJORDOMUS = 1
    MAJORPLANET = 2


class User(UserMixin, db.Model):
    """ Model tabulky `user`

    Třida definující model databázové tabulky user
    """
    __tablename__ = "user"
    id_user = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False)
    password_hash = db.Column(db.String, nullable=False)
    first_name = db.Column(db.String(64), nullable=False)
    last_name = db.Column(db.String(64), nullable=False, unique=True)
    gender = db.Column(db.Enum(Gender), nullable=False)
    habitat_id = db.Column(db.Integer, db.ForeignKey('habitat.id_habitat'), nullable=False)
    role = db.Column(db.Enum(Role), nullable=False, default=Role.COLONIZER)

    def get_id(self) -> int:
        """ Funkce pro získání ID uživatele.

        Funkce je vyžadována modulem `flask_login` v případě, že primární klíč tabulky uživatele se jmenuje jinak než
        `ID`.

        :return: identifikační číslo uživatele

         """
        return int(self.id_user)

    def __init__(self, username: str, password_hash: str, first_name: str, last_name: str, gender: Gender,
                 habitat_id: int, role=Role.COLONIZER) -> None:
        """ Obecný konstruktor třídy `User`

        Pomocí tohoto konstruktoru lze nastavit všechny parametry, kromě ID, které si databázový systém nastavuje sám

        :param username: Přihlašovací jméno
        :param password_hash: Hash hesla
        :param first_name: Křestní jméno uživatele
        :param last_name: Příjmení uživatele
        :param gender: Pohlaví uživatele. Může nabývat hodnoty definované v enumeraci `Gender`
        :param habitat_id: Identifikace cizího klíče popisující habitat, ve kterém uživatel žije
        :param role: Role uživatele. Nabývá hodnot z enumerace Role. Výchozí hodnota je Role.COLONIZER
        """

        self.username = username
        self.password_hash = password_hash
        self.first_name = first_name
        self.last_name = last_name
        self.gender = gender
        self.habitat_id = habitat_id
        self.role = role

    def __repr__(self) -> str:
        return f"< User (id {self.id_user}), {self.username} -  {self.first_name} {self.last_name}, " \
               f"{self.gender} | {self.role}> @ Base ID:{self.habitat_id}>"


class Habitat(db.Model):
    """ Model tabulky 'habitat'

    Třída definující model tabulky `habitat` v databázi
    """
    __tablename__ = 'habitat'
    id_habitat = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), unique=True, nullable=False)
    maximum_inhabitants = db.Column(db.Integer, nullable=False, default=32)
    x_position = db.Column(db.Float, nullable=False, default=0.0)
    y_position = db.Column(db.Float, nullable=False, default=0.0)
    inhabitants = db.relation("User", backref='habitat')

    def __repr__(self) -> str:
        return f"< Base (id {self.id_habitat}) {self.name} @ [{self.x_position}; {self.y_position}]>"

    def __init__(self, name: str, x_position: float, y_position: float, maximum_inhabitants=32) -> None:
        """ Obecný konstruktor třídy Habitat

        Pomocí tohoto konstruktoru lze nastavit všechny atributy třídy `Habitat`
        Atribut `id_habitat` je později nastaven databázovým systémem, do té doby má hodnotu `None`

        :param name: Jméno základny
        :param x_position: souřadnice X polohy základny
        :param y_position: souřadnice Y polohy základny
        :param maximum_inhabitants: Maximální počet obyvatel. Výchozí hodnota je 32
        """
        self.name = name
        self.maximum_inhabitants = maximum_inhabitants
        self.x_position = x_position
        self.y_position = y_position

colonize/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, length


class LoginForm(FlaskForm):
    username = StringField(label="Uživatelské jméno",
                           validators=[
                               DataRequired(message="Musíte zadat uživatelské jméno"),
                               length(min=3, max=64, message="Uživatelské jméno být dlouhé v rozmezí 3-64 znaků")
                           ])
    password = PasswordField(label="Heslo",
                             validators=[
                                 DataRequired(message="Musíte zadat heslo")
                             ])

    remember = BooleanField("Zapamatovat si přihlášení")
    submit = SubmitField("Přihlásit se")

colonize/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

# login_manager = LoginManager()


app = Flask(__name__)
app.config.from_pyfile('settings.py')

""" 
Inicializace rozšíření aplikace
"""
db = SQLAlchemy(app)
login_manager = LoginManager(app)
login_manager.init_app(app)
login_manager.login_view = "auth.login_page"

"""
Načtení jednotlivých blueprintů, ze kterých se aplikace skládá
"""
from .main import main as main_blueprint

app.register_blueprint(main_blueprint)

from .auth import auth as auth_blueprint

app.register_blueprint(auth_blueprint)

from .error import ErrorPages

app.register_error_handler(403, ErrorPages.error_403)
app.register_error_handler(404, ErrorPages.error_404)
app.register_error_handler(500, ErrorPages.error_500)

colonize/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

colonize/main/views.py
from flask import render_template, abort
from flask_login import login_required, current_user
from sqlalchemy import desc
from . import main
from colonize.models import Habitat, User, Role


@main.route('/dashboard')
@main.route('/')
@login_required
def dashboard():
    user_habitat = Habitat.query.filter_by(id_habitat=current_user.habitat_id).first()
    if user_habitat is None:
        return abort(500)

    data = {
        'user_habitat': user_habitat
    }
    return render_template('pages/dashboard.html', title='Domovská stránka', data=data)


@main.route('/habitat/<int:id_habitat>')
def habitat_overview(id_habitat: int):
    habitat = Habitat.query.filter_by(id_habitat=id_habitat).first()
    if habitat is None:
        return abort(404)

    inhabitants = User.query.filter_by(habitat_id=id_habitat).order_by(desc(User.role)).all()
    majordomus = User.query.filter_by(role=Role.MAJORDOMUS).first()

    data = {
        'habitat': habitat,
        'inhabitants': inhabitants,
        'number_of_inhabitants': len(inhabitants),
        'majordomus': majordomus
    }

    return render_template('pages/habitat_overview.html', title=f'Základna {data["habitat"].name} ', data=data)

colonize/templates/base.html
<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>{{ title }} | Colonize App</title>
</head>

<body>
{% include 'components/_navbar.html' %}

<main>
    {% block content %}

    {% endblock content %}
</main>

{% include 'components/_footer.html' %}
</body>

</html>

colonize/templates/components/_footer.html
<footer>

</footer>

colonize/templates/components/_navbar.html
<nav>
    <ul>
        {% if current_user.is_authenticated %}
        <li>{{ current_user.username}}</li>
        <li><a href="{{url_for('main.dashboard')}}">Domů</a></li>
        <li><a href="{{ url_for('auth.logout') }}">Odhlásit se</a></li>
        {% else %}
        <li><a href="{{ url_for('auth.login_page') }}">Přihlas se</a></li>
        {% endif %}
    </ul>
</nav>

colonize/templates/pages/dashboard.html
{% extends 'base.html' %}

{% block content %}
<p>Vítej uživateli {{current_user.username}}</p>
<p>Bydlíš na <a href="{{ url_for('main.habitat_overview', id_habitat=current_user.habitat_id) }}">základně {{
    data.user_habitat.name }}</a>, která se nachází na souřadnicích [{{data.user_habitat.x_position}};
    {{data.user_habitat.y_position}}]</p>
{% endblock content %}
    

colonize/templates/pages/habitat_overview.html
{% extends 'base.html' %}

{% block content %}
<h1>Základna {{ data.habitat.name }}</h1>
<p>Pozice x: {{data.habitat.x_position}}; y: {{data.habitat.y_position}}</p>
{% if data.majordomus %}
<p>Majordomus: {{data.majordomus.first_name}} {{data.majordomus.last_name}}</p>
{% else %}
<p>Základna nemá majordoma</p>
{% endif %}


<h2>Obyvatelé základny ({{data.number_of_inhabitants}}/{{data.habitat.maximum_inhabitants}}) </h2>
{% if data.inhabitants %}
<table>
    <tr>
        <th>Jméno</th>
        <th>Pohlaví</th>
        <th>Role</th>
    </tr>
    {% for person in data.inhabitants %}
    <tr>
        <td>{{person.first_name}} {{person.last_name}}</td>
        <td>{{person.gender}}</td>
        <td>{{person.role}}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<span>Na základně nikdo nebydlí</span>
{% endif %}

{% endblock content %}

colonize/templates/pages/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Přihlášení</h2>
<form method="post">
    {{ form.hidden_tag() }}

    {{ form.username.label() }}
    {% if form.username.errors %}
    <ul>
        {% for error in form.username.errors %}
        <li> {{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {{ form.username() }}

    {{ form.password.label() }}
    {% if form.password.errors %}
    <ul>
        {% for error in form.password.errors %}
        <li> {{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {{ form.password() }}

    {{ form.remember.label() }}
    {{ form.remember() }}

    {{ form.submit.label() }}
    {{ form.submit() }}

</form>
{% endblock %}